"""cell, cell_source, extraction_run

Revision ID: 34afb6206cf6
Revises: c0b0786a2089
Create Date: 2026-06-08 17:48:50.999704
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '34afb6206cf6'
down_revision: str | None = 'c0b0786a2089'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_db_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'canceled')", name='ck_extraction_run_status'),
    sa.ForeignKeyConstraint(['document_db_id'], ['document_db.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.Column('last_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('high', 'medium', 'low')", name='ck_cell_confidence'),
    sa.CheckConstraint("extraction_method IN ('full_context', 'retrieval_fallback')", name='ck_cell_method'),
    sa.CheckConstraint("extraction_status IN ('idle', 'queued', 'running', 'done', 'error')", name='ck_cell_extraction_status'),
    sa.CheckConstraint("review_status IN ('unreviewed', 'verified', 'edited', 'rejected')", name='ck_cell_review_status'),
    sa.ForeignKeyConstraint(['column_id'], ['document_column.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_run_id'], ['extraction_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'column_id', name='uq_cell_doc_col')
    )
    op.create_index(op.f('ix_cell_column_id'), 'cell', ['column_id'], unique=False)
    op.create_index(op.f('ix_cell_document_id'), 'cell', ['document_id'], unique=False)
    op.create_table('cell_source',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cell_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cell.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunk.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_source_cell_id'), 'cell_source', ['cell_id'], unique=False)
    # NOTE: autogenerate falsely flags the pgvector hnsw index for drop (it can't
    # introspect the custom index). Intentionally NOT dropping it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_source_cell_id'), table_name='cell_source')
    op.drop_table('cell_source')
    op.drop_index(op.f('ix_cell_document_id'), table_name='cell')
    op.drop_index(op.f('ix_cell_column_id'), table_name='cell')
    op.drop_table('cell')
    op.drop_table('extraction_run')
    # ### end Alembic commands ###
